apiVersion: v1
kind: Service
metadata:
  name: project-app
  namespace: project-namespace
spec:
  type: ClusterIP
  selector:
    app: project-app
  ports:
    - name: front-http-port
      port: 2345
      targetPort: 80 # react app served by nginx